### ISSUE TITLE
Projects deprecated

### ISSUE THREAD

**Issue by giannisdaras** [TEDxNTUA/tedxntua2019#22]
Current projects are deprecated. The due dates have passed and there is no update in the achieved goals.
I think that the benefits of having a project for each discrete goal is a bit overkill for a team of three persons, who communicate in a daily basis. The time needed to create them, explain them and keep them updated could be used efficiently for coding.

I propose we abandon the idea of having them. If we need something for internal tasks management, we could use one single project, containing smaller tasks that could be frequently passed among the cards (TODO, Done, In progress).

**Comment by tdiam** [comment]
The [flat pages](https://github.com/TEDxNTUA/tedxntua2019/projects/5) can be cancelled, I think we've settled on independent applications.
Internationalization can stay, at least to outline Stage 3.
I wasn't planning on writing any more projects so :+1: in general.
